version: "3"
services:
  springboot-customer-service:
    image: springboot-customer-service
    container_name: customer-service-container
    ports:
      - "8082:8082"
    networks:
      - customer-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    volumes: 
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d/:ro
    restart: always
    networks:
      - customer-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo  

networks:
  customer-mysql: